#!/usr/bin/env bash

# this is where opensim3's headers + libs are placed post-build
mkdir -p opensim3-scone/install
install_dir="${PWD}/opensim3-scone/install"

mkdir -p opensim3-scone/build
cd opensim3-scone/build
cmake .. \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE-Release}" \
      -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE:-TRUE}" \
      -DSIMBODY_HOME="../../simbody/install" \
      -DCMAKE_INSTALL_PREFIX="${install_dir}"
make -j$(nproc)

# create the relevant include/ and lib/ dirs that scone needs
make install
cd -
